version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:3000
    volumes:
      - .:/app
      - "/app/node_modules"
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:5.7.34
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=user
      - MYSQL_DATABASE=todo_list
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=9999
